`timescale 1ns / 1ps

////////////////////////
// This file was automatically generated by CATE
// Comments and Notes: 
////////////////////////

module adder_4bit_sim; //no ports to test module

    // declare inputs and outputs for your module
    // can be the same names as the ports of the module under test
    logic [3:0] A;
    logic [3:0] B;
    logic [3:0] S; 
    logic Cin,Cout;
    logic mode;
    
    //Instantiate your module undertest
    Adder_4bit my_adder (  .A(A), .B(B), .Cin(Cin), .S(S), .Cout(Cout), .mode(mode));

    //list your test cases
    initial 
    
        begin
        
        //saturation test cases 
        A = 4'b1111; B = 4'b0001; mode = 1; Cin = 0; //1111
        //if (S[3:0] != 4'b1110) $display("Error b0:%S[0] b1:%S[1] b2:%S[2] b3:%S[3] Cin:%Cin Cout:%Cout" , S[0], S[1], S[2], S[3], Cin, Cout);
        #10
        
        A = 4'b0001; B = 4'b0010; mode = 1; Cin = 0; //0011
        #10
        
        A = 4'b0111; B = 4'b0001; mode = 1; Cin = 0; //1000
        #10
        
        A = 4'b0111; B = 4'b1000; mode = 1; Cin = 0; //1111
        #10
        
        A = 4'b1010; B = 4'b0101; mode = 1; Cin = 0; //1111, no overflow
        #10
        
        A = 4'b0000; B = 4'b0000; mode = 1; Cin = 1; //0001
        #10
        
        A = 4'b0000; B = 4'b0000; mode = 1; Cin = 0; //0000
        #50
        
        //wrap around test cases
        A = 4'b1111; B = 4'b0001; mode = 0; Cin = 0; //0000
        #10
       
        A = 4'b0001; B = 4'b0010; mode = 0; Cin = 0; //0011
        #10
        
        A = 4'b0111; B = 4'b0001; mode = 0; Cin = 0; //1000
        #10
        
        A = 4'b0111; B = 4'b1000; mode = 0; Cin = 0; //1111
        #10
        
        A = 4'b1010; B = 4'b0101; mode = 0; Cin = 0; //1111, no overflow
        #10
        
        A = 4'b0000; B = 4'b0000; mode = 0; Cin = 1; //0001
        #10
        
        A = 4'b0000; B = 4'b0000; mode = 0; Cin = 0; //0000
        #10
        
//	// THIS MAY NOT BE CORRECT...!
//        A = 1111; B = 0001; mode = 0; Cin = 0;
//        #10

//        A = 0011; B = 0001; Cin = 0;
//        #10

       $display("Finished");  
      end                                 
    
endmodule

