`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 10/19/2022 04:44:32 PM
// Design Name: 
// Module Name: FA4
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


`timescale 1ns / 1ps

////////////////////////
// This file was automatically generated by CATE
////////////////////////

module Full_Adder(
	input A,
	input B,
	input  Cin,
	output S,
	output  Cout
	);

	assign S = ~Cout & (A | B | Cin) | (A & B & Cin);
	assign Cout = (A & Cin) | (B & Cin) | (A & B);
	
endmodule
