`timescale 1ns / 1ps

////////////////////////
// This file was automatically generated by CATE
////////////////////////

module Full_Adder(
	input A,
	input B,
	input  Cin,
	output logic S,
	output  Cout
	);

	assign S = ~Cout & (A | B | Cin) | (A & B & Cin);
	assign Cout = (A & Cin) | (B & Cin) | (A & B);
	
endmodule

